// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt9jjJ_SDBbqT1FE6l5TJDnVq1TPkOxvE',
    appId: '1:933286018701:web:fd2850d1ba32ae5bc4acc4',
    messagingSenderId: '933286018701',
    projectId: 'shieldher-6eca0',
    authDomain: 'shieldher-6eca0.firebaseapp.com',
    storageBucket: 'shieldher-6eca0.firebasestorage.app',
    measurementId: 'G-G595NH3G3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf_q_OhVqvwJ22Wi_bCRpjA7KFRsx3BQ8',
    appId: '1:933286018701:android:cf89c9753b8de69bc4acc4',
    messagingSenderId: '933286018701',
    projectId: 'shieldher-6eca0',
    storageBucket: 'shieldher-6eca0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg5q6TyYGtLsckJngyZ6HqZWZiasaTxKI',
    appId: '1:933286018701:ios:66cdc648a7eb3fa1c4acc4',
    messagingSenderId: '933286018701',
    projectId: 'shieldher-6eca0',
    storageBucket: 'shieldher-6eca0.firebasestorage.app',
    iosBundleId: 'com.example.womenSafety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg5q6TyYGtLsckJngyZ6HqZWZiasaTxKI',
    appId: '1:933286018701:ios:66cdc648a7eb3fa1c4acc4',
    messagingSenderId: '933286018701',
    projectId: 'shieldher-6eca0',
    storageBucket: 'shieldher-6eca0.firebasestorage.app',
    iosBundleId: 'com.example.womenSafety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt9jjJ_SDBbqT1FE6l5TJDnVq1TPkOxvE',
    appId: '1:933286018701:web:78c049e45d192af5c4acc4',
    messagingSenderId: '933286018701',
    projectId: 'shieldher-6eca0',
    authDomain: 'shieldher-6eca0.firebaseapp.com',
    storageBucket: 'shieldher-6eca0.firebasestorage.app',
    measurementId: 'G-02F5MP575P',
  );
}
